//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trash2012.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trash2012.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap BlueHouseBot {
            get {
                object obj = ResourceManager.GetObject("BlueHouseBot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BlueHouseTop {
            get {
                object obj = ResourceManager.GetObject("BlueHouseTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BrownHouse {
            get {
                object obj = ResourceManager.GetObject("BrownHouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CalendarBackground {
            get {
                object obj = ResourceManager.GetObject("CalendarBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CamionIntro {
            get {
                object obj = ResourceManager.GetObject("CamionIntro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] CustomMap {
            get {
                object obj = ResourceManager.GetObject("CustomMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap DechetterieBottomLeft {
            get {
                object obj = ResourceManager.GetObject("DechetterieBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DechetterieTopLeft {
            get {
                object obj = ResourceManager.GetObject("DechetterieTopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DechetterieTopRight {
            get {
                object obj = ResourceManager.GetObject("DechetterieTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] DefaultMap {
            get {
                object obj = ResourceManager.GetObject("DefaultMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForestBottomLeft {
            get {
                object obj = ResourceManager.GetObject("ForestBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForestBottomMiddle {
            get {
                object obj = ResourceManager.GetObject("ForestBottomMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForestBottomRight {
            get {
                object obj = ResourceManager.GetObject("ForestBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForestMiddle {
            get {
                object obj = ResourceManager.GetObject("ForestMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForestMiddleLeft {
            get {
                object obj = ResourceManager.GetObject("ForestMiddleLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForestMiddleRight {
            get {
                object obj = ResourceManager.GetObject("ForestMiddleRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForestSolo {
            get {
                object obj = ResourceManager.GetObject("ForestSolo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForestTopLeft {
            get {
                object obj = ResourceManager.GetObject("ForestTopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForestTopMiddle {
            get {
                object obj = ResourceManager.GetObject("ForestTopMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForestTopRight {
            get {
                object obj = ResourceManager.GetObject("ForestTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GarbageEmpty {
            get {
                object obj = ResourceManager.GetObject("GarbageEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GarbageFull {
            get {
                object obj = ResourceManager.GetObject("GarbageFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap intro {
            get {
                object obj = ResourceManager.GetObject("intro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap intro1 {
            get {
                object obj = ResourceManager.GetObject("intro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap intro2 {
            get {
                object obj = ResourceManager.GetObject("intro2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap intro3 {
            get {
                object obj = ResourceManager.GetObject("intro3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Missing {
            get {
                object obj = ResourceManager.GetObject("Missing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une ville est en proie à la saleté et aux déchets qui s&apos;accumulent !
        ///Aidez la en faisant les choix judicieux pour nettoyer au mieux cette ville !.
        /// </summary>
        public static string NewGameAnnounce {
            get {
                return ResourceManager.GetString("NewGameAnnounce", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap NormalHouse {
            get {
                object obj = ResourceManager.GetObject("NormalHouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RedHouseBot {
            get {
                object obj = ResourceManager.GetObject("RedHouseBot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RedHouseTop {
            get {
                object obj = ResourceManager.GetObject("RedHouseTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TilePlain {
            get {
                object obj = ResourceManager.GetObject("TilePlain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadBottomLeft {
            get {
                object obj = ResourceManager.GetObject("TileRoadBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadBottomLeftRight {
            get {
                object obj = ResourceManager.GetObject("TileRoadBottomLeftRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadBottomRight {
            get {
                object obj = ResourceManager.GetObject("TileRoadBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadHorizontal {
            get {
                object obj = ResourceManager.GetObject("TileRoadHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadTopBottomLeft {
            get {
                object obj = ResourceManager.GetObject("TileRoadTopBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadTopBottomRight {
            get {
                object obj = ResourceManager.GetObject("TileRoadTopBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadTopLeft {
            get {
                object obj = ResourceManager.GetObject("TileRoadTopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadTopLeftRight {
            get {
                object obj = ResourceManager.GetObject("TileRoadTopLeftRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadTopRight {
            get {
                object obj = ResourceManager.GetObject("TileRoadTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadVertical {
            get {
                object obj = ResourceManager.GetObject("TileRoadVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckBottomLeft {
            get {
                object obj = ResourceManager.GetObject("TruckBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckBottomRight {
            get {
                object obj = ResourceManager.GetObject("TruckBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckBottomTop {
            get {
                object obj = ResourceManager.GetObject("TruckBottomTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckLeftBottom {
            get {
                object obj = ResourceManager.GetObject("TruckLeftBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckLeftRight {
            get {
                object obj = ResourceManager.GetObject("TruckLeftRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckLetfTop {
            get {
                object obj = ResourceManager.GetObject("TruckLetfTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckPaper {
            get {
                object obj = ResourceManager.GetObject("TruckPaper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckRightBottom {
            get {
                object obj = ResourceManager.GetObject("TruckRightBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckRightLeft {
            get {
                object obj = ResourceManager.GetObject("TruckRightLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckRightTop {
            get {
                object obj = ResourceManager.GetObject("TruckRightTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckTopBottom {
            get {
                object obj = ResourceManager.GetObject("TruckTopBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckTopLeft {
            get {
                object obj = ResourceManager.GetObject("TruckTopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckTopRight {
            get {
                object obj = ResourceManager.GetObject("TruckTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
