//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trash2012.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trash2012.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap CalendarBackground {
            get {
                object obj = ResourceManager.GetObject("CalendarBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CamionIntro {
            get {
                object obj = ResourceManager.GetObject("CamionIntro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] CustomMap {
            get {
                object obj = ResourceManager.GetObject("CustomMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] DefaultMap {
            get {
                object obj = ResourceManager.GetObject("DefaultMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap HouseHorizontalEmpty {
            get {
                object obj = ResourceManager.GetObject("HouseHorizontalEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HouseHorizontalFull {
            get {
                object obj = ResourceManager.GetObject("HouseHorizontalFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HouseVerticalEmpty {
            get {
                object obj = ResourceManager.GetObject("HouseVerticalEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HouseVerticalFull {
            get {
                object obj = ResourceManager.GetObject("HouseVerticalFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap intro {
            get {
                object obj = ResourceManager.GetObject("intro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap intro1 {
            get {
                object obj = ResourceManager.GetObject("intro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap intro2 {
            get {
                object obj = ResourceManager.GetObject("intro2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap intro3 {
            get {
                object obj = ResourceManager.GetObject("intro3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LeftBottom {
            get {
                object obj = ResourceManager.GetObject("LeftBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LeftBottom_long_ {
            get {
                object obj = ResourceManager.GetObject("LeftBottom_long_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LeftRight {
            get {
                object obj = ResourceManager.GetObject("LeftRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LeftRight_long_ {
            get {
                object obj = ResourceManager.GetObject("LeftRight_long_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] music {
            get {
                object obj = ResourceManager.GetObject("music", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une ville est en proie à la saleté et aux déchets qui s&apos;accumulent !
        ///Aidez la en faisant les choix judicieux pour nettoyer au mieux cette ville !.
        /// </summary>
        public static string NewGameAnnounce {
            get {
                return ResourceManager.GetString("NewGameAnnounce", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap RightLeft {
            get {
                object obj = ResourceManager.GetObject("RightLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TilePlain {
            get {
                object obj = ResourceManager.GetObject("TilePlain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadBottomLeft {
            get {
                object obj = ResourceManager.GetObject("TileRoadBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadBottomLeftRight {
            get {
                object obj = ResourceManager.GetObject("TileRoadBottomLeftRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadBottomRight {
            get {
                object obj = ResourceManager.GetObject("TileRoadBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadHorizontal {
            get {
                object obj = ResourceManager.GetObject("TileRoadHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadTopBottomLeft {
            get {
                object obj = ResourceManager.GetObject("TileRoadTopBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadTopBottomRight {
            get {
                object obj = ResourceManager.GetObject("TileRoadTopBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadTopLeft {
            get {
                object obj = ResourceManager.GetObject("TileRoadTopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadTopLeftRight {
            get {
                object obj = ResourceManager.GetObject("TileRoadTopLeftRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadTopRight {
            get {
                object obj = ResourceManager.GetObject("TileRoadTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TileRoadVertical {
            get {
                object obj = ResourceManager.GetObject("TileRoadVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TopBottom {
            get {
                object obj = ResourceManager.GetObject("TopBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TopBottom_long_ {
            get {
                object obj = ResourceManager.GetObject("TopBottom_long_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckTopRight {
            get {
                object obj = ResourceManager.GetObject("TruckTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TruckPaper {
            get {
                object obj = ResourceManager.GetObject("TruckPaper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
